// UCS-1158 — the derived layer: plural browse trees, synthesized call numbers,
// a resolution index. Regenerable, disposable, and load-bearing for nothing.
//
// Tested through its public seam: the CLI process — exit codes and output ARE
// the contract. The assertions are golden-file style in this repo's idiom: full
// stable-sorted projections compared against literal expectations, which works
// only because the output carries no timestamps and stable-sorts everything.
//
// The five acceptance criteria map onto the sections below:
//   1  two axes from one flat store, stable-sorted        -> 'plural axes'
//   2  call numbers are display strings, never identity   -> 'call numbers'
//   3  delete + regenerate is byte-identical              -> 'round trip'
//   4  stale and draft leaves visibly demoted, not hidden -> 'demotion'
//   5  embedding recall has a slot and a gate, no impl    -> 'recall slot'
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { chmodSync, cpSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { AXES } from '../payload/engine/lib/derived.js';
import { ID_GRAMMARS, idPattern } from '../payload/engine/lib/id-grammars.js';

const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const cli = join(repoRoot, 'payload', 'engine', 'derive.js');
const fixture = (name) => join(repoRoot, 'tests', 'fixtures', 'derived', name);

/** The injected date every test measures staleness against. Never the clock. */
const TODAY = '2026-08-16';

/** A writable copy of a fixture store — the derived layer is written into it. */
function scratch(t, name = 'store') {
  const dir = mkdtempSync(join(tmpdir(), 'uk-derived-'));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  cpSync(fixture(name), dir, { recursive: true });
  return dir;
}

function derive(root, args = []) {
  const r = spawnSync(process.execPath, [cli, '--root', root, ...args], { encoding: 'utf8' });
  return { ...r, json: r.stdout.startsWith('{') ? JSON.parse(r.stdout) : null };
}

const derivedFile = (root, name) => readFileSync(join(root, 'knowledge', 'derived', name), 'utf8');

/** Every file under the derived directory, relative and forward-slashed. */
function derivedFiles(root) {
  return readdirSync(join(root, 'knowledge', 'derived'), { recursive: true })
    .map(String)
    .sort();
}

// ------------------------------------------------------------- 1 · plural axes

test('generation produces browse trees along two axes from one flat store', (t) => {
  const root = scratch(t);
  const r = derive(root, ['--today', TODAY, '--write', '--json']);
  assert.equal(r.status, 0, r.stderr);

  // Plural, and named by the axis table rather than by this test — a third axis
  // is a row in AXES, and this assertion follows it there.
  assert.deepEqual(
    r.json.artifacts,
    ['knowledge/derived/index.json', ...AXES.map((a) => `knowledge/derived/tree.${a.key}.md`)].sort(),
  );
  assert.deepEqual(AXES.map((a) => a.key), ['domain-form', 'form-domain'],
    'the two shipped axes are domain-first for stewards and form-first for agents');

  // The SAME leaves, projected two ways: one flat store, two orderings. The
  // domain-first tree opens on a domain node, the form-first one on a form.
  const domainFirst = derivedFile(root, 'tree.domain-form.md');
  const formFirst = derivedFile(root, 'tree.form-domain.md');
  assert.match(domainFirst, /^- \*\*design-system\/\*\* \(3\)$/m);
  assert.match(formFirst, /^- \*\*constraint\/\*\* \(3\)$/m);
  assert.notEqual(domainFirst, formFirst, 'two axes are two trees, not one tree twice');

  // Every leaf appears in BOTH trees — a projection reorders the store, it
  // never selects from it.
  for (const id of ['L-000117', 'L-000133', 'L-000162', 'L-000171', 'L-000213', 'L-000228']) {
    assert.ok(domainFirst.includes(id), `${id} is missing from the domain-first tree`);
    assert.ok(formFirst.includes(id), `${id} is missing from the form-first tree`);
  }
});

test('the golden domain-first tree — the whole artifact, byte for byte', (t) => {
  const root = scratch(t);
  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);
  assert.equal(derivedFile(root, 'tree.domain-form.md'), `# Browse tree — domain → form

> DERIVED — regenerated by \`node payload/engine/derive.js --write\`. Do not edit; do not cite. Deleting this directory loses nothing.

- axis: \`domain-form\` (domain → form)
- for: stewards — subject matter first, the way a person holds a library in their head
- leaves: 6
- time verdicts: checked against --today 2026-08-16 (stale after 365 days for stable, 90 for volatile; static never stales)

Call numbers are synthesized display strings for this projection only. They
are NOT identities: cite the accession id (L-NNNNNN), never a call number.

- **brand/** (1)
  - **identity/** (1)
    - **reference/** (1)
      - \`BRA/IDE/REF·L-000228\` Brand color token table
- **design-system/** (3)
  - **components/** (3)
    - **constraint/** (2)
      - \`DES/COM/CON·L-000133\` Contrast ratios at token export
      - \`DES/COM/CON·L-000213\` Component render budget — **demoted** (stage)
        - stage: stage "draft" is pre-promotion — no moderator has certified this leaf's citations (UCS-1149)
    - **reference/** (1)
      - \`DES/COM/REF·L-000117\` Icon component sizing quirks
- **engineering/** (2)
  - **frontend/** (2)
    - **constraint/** (1)
      - \`ENG/FRO/CON·L-000162\` Bundle-size budget thresholds — **demoted** (time)
        - time: verified 223 day(s) ago, past the 90-day limit for volatile knowledge (UCS-1150)
    - **runbook/** (1)
      - \`ENG/FRO/RUN·L-000171\` Visual regression triage playbook — **demoted** (stage, time)
        - stage: stage "draft" is pre-promotion — no moderator has certified this leaf's citations (UCS-1149)
        - time: verified 154 day(s) ago, past the 90-day limit for volatile knowledge (UCS-1150)
`);
});

test('trees are stable-sorted: the reordered twin generates identical bytes', (t) => {
  // The twin holds the same six leaves with the catalog reversed and every leaf
  // FILE renamed, so the loader's directory walk hands them over in a different
  // sequence. A tree whose shape depended on that sequence would differ here.
  const a = scratch(t, 'store');
  const b = scratch(t, 'store-reordered');
  assert.equal(derive(a, ['--today', TODAY, '--write']).status, 0);
  assert.equal(derive(b, ['--today', TODAY, '--write']).status, 0);

  for (const axis of AXES) {
    assert.equal(
      derivedFile(b, `tree.${axis.key}.md`),
      derivedFile(a, `tree.${axis.key}.md`),
      `the ${axis.key} tree must not depend on the order the loader enumerated leaves`,
    );
  }

  // The index agrees too, once the `file` values — which name real paths and are
  // content rather than order — are set aside.
  const strip = (root) => JSON.parse(derivedFile(root, 'index.json')).leaves
    .map(({ file, ...rest }) => rest);
  assert.deepEqual(strip(b), strip(a));
});

// ----------------------------------------------------------- 2 · call numbers

test('call numbers are synthesized into the trees, one per axis', (t) => {
  const root = scratch(t);
  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);

  // The SAME leaf carries a different call number in each tree, because a call
  // number describes a POSITION in a projection and that leaf holds two.
  assert.match(derivedFile(root, 'tree.domain-form.md'), /`DES\/COM\/REF·L-000117`/);
  assert.match(derivedFile(root, 'tree.form-domain.md'), /`REF\/DES\/COM·L-000117`/);

  const index = JSON.parse(derivedFile(root, 'index.json'));
  const leaf = index.leaves.find((l) => l.id === 'L-000117');
  assert.equal(leaf.positions['domain-form']['call-number'], 'DES/COM/REF·L-000117');
  assert.equal(leaf.positions['form-domain']['call-number'], 'REF/DES/COM·L-000117');
});

test('no call number is an id in ANY id space — checked against every grammar', (t) => {
  const root = scratch(t);
  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);
  const index = JSON.parse(derivedFile(root, 'index.json'));

  // Enumerates ID_GRAMMARS rather than a remembered list, so a NEW id space
  // that happened to accept call numbers fails here the day it is added.
  const spaces = Object.keys(ID_GRAMMARS);
  assert.ok(spaces.includes('leaf-ref') && spaces.includes('accessions'));

  let checked = 0;
  for (const leaf of index.leaves) {
    for (const position of Object.values(leaf.positions)) {
      const callNumber = position['call-number'];
      for (const space of spaces) {
        assert.ok(
          !idPattern(space).test(callNumber),
          `call number ${callNumber} is accepted by the "${space}" id grammar — a display string became citable`,
        );
      }
      checked += 1;
    }
  }
  assert.equal(checked, 12, 'six leaves across two axes');
});

test('the index keys leaves by accession and never by call number', (t) => {
  const root = scratch(t);
  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);
  const index = JSON.parse(derivedFile(root, 'index.json'));

  assert.deepEqual(index.leaves.map((l) => l.id),
    ['L-000117', 'L-000133', 'L-000162', 'L-000171', 'L-000213', 'L-000228']);
  // A lookup table is the most tempting place to reintroduce a second
  // resolvable name for a leaf. There is no top-level map from call number to
  // anything, and the index says so in its own text.
  assert.match(index['call-numbers'], /NOT identities and never citable/);
  assert.equal(index.note.includes('do not cite'), true);
});

// -------------------------------------------------------------- 3 · round trip

test('deleting the derived layer and regenerating yields byte-identical bytes', (t) => {
  const root = scratch(t);
  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);

  const before = new Map(derivedFiles(root).map((f) => [f, derivedFile(root, f)]));
  assert.ok(before.size >= 3);

  // Delete the whole layer. Nothing is lost by construction — that is the
  // claim, and this is the test of it.
  rmSync(join(root, 'knowledge', 'derived'), { recursive: true, force: true });

  // The store still loads and still validates with the layer gone: no other
  // surface depends on it.
  const validate = spawnSync(process.execPath, [join(repoRoot, 'payload', 'engine', 'validate.js'), '--root', root, '--json'], { encoding: 'utf8' });
  assert.equal(validate.status, 0, `the store must be clean without its derived layer\n${validate.stdout}${validate.stderr}`);

  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);
  const after = new Map(derivedFiles(root).map((f) => [f, derivedFile(root, f)]));

  assert.deepEqual([...after.keys()], [...before.keys()]);
  for (const [file, text] of before) {
    assert.equal(after.get(file), text, `${file} did not regenerate byte-identically`);
  }
});

test('--check reports a missing, stale, or unexpected artifact as findings', (t) => {
  const root = scratch(t);

  // Missing: nothing generated yet.
  const missing = derive(root, ['--today', TODAY, '--json']);
  assert.equal(missing.status, 1, 'an ungenerated layer is FINDINGS, not a crash');
  assert.deepEqual([...new Set(missing.json.findings.map((f) => f.code))], ['derived-missing']);

  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);
  assert.equal(derive(root, ['--today', TODAY, '--json']).status, 0, 'a freshly written layer checks clean');

  // Stale: a hand-edited artifact is reported rather than believed.
  writeFileSync(join(root, 'knowledge', 'derived', 'tree.domain-form.md'), '# edited by hand\n');
  const stale = derive(root, ['--today', TODAY, '--json']);
  assert.equal(stale.status, 1);
  assert.deepEqual(stale.json.findings.map((f) => [f.code, f.file]),
    [['derived-stale', 'knowledge/derived/tree.domain-form.md']]);

  // Unexpected: a file no axis generates would be deleted by a regeneration, so
  // it must never live here.
  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);
  writeFileSync(join(root, 'knowledge', 'derived', 'notes.md'), 'hand-written\n');
  const unexpected = derive(root, ['--today', TODAY, '--json']);
  assert.equal(unexpected.status, 1);
  assert.deepEqual(unexpected.json.findings.map((f) => [f.code, f.file]),
    [['derived-unexpected', 'knowledge/derived/notes.md']]);
});

test('only ENOENT is an absent layer — an unreadable one exits 2, never findings', (t) => {
  // The distinction the exit-code contract rests on. An absent derived layer is
  // the ordinary state of a fresh clone and reports `derived-missing` (exit 1,
  // fix by regenerating). A layer the engine could not LOOK at is a different
  // fact entirely: nothing was compared, so reporting findings would tell an
  // agent the check ran when it never did (PRD §5).

  // ENOTDIR — something is squatting on the directory's name. Classified as an
  // ERROR rather than "absent" on purpose: the layer is not missing, it is
  // corrupted, and `--write` would have to delete a file the engine never made.
  const squatted = scratch(t);
  writeFileSync(join(squatted, 'knowledge', 'derived'), 'not a directory\n');
  const notdir = derive(squatted, ['--today', TODAY]);
  assert.equal(notdir.status, 2, 'a file squatting on the derived directory is exit 2, not findings');
  assert.match(notdir.stderr, /could not be READ, so nothing was checked/);
  assert.match(notdir.stderr, /this is not a stale layer/);

  // EACCES — the directory exists and cannot be read.
  const locked = scratch(t);
  assert.equal(derive(locked, ['--today', TODAY, '--write']).status, 0);
  const derivedDir = join(locked, 'knowledge', 'derived');
  chmodSync(derivedDir, 0o000);
  const denied = derive(locked, ['--today', TODAY]);
  // Restored immediately rather than in a t.after hook: the scratch cleanup is
  // also an after hook, and an unreadable directory cannot be removed — the
  // teardown would fail on a test whose assertions all passed.
  chmodSync(derivedDir, 0o755);
  // Running as root defeats permission bits entirely; skip rather than assert a
  // falsehood about the environment.
  if (denied.status !== 0) {
    assert.equal(denied.status, 2, 'an unreadable derived layer is exit 2, never findings');
    assert.match(denied.stderr, /could not be READ, so nothing was checked/);
  }

  // ENOENT — the contrast case. Absent IS the ordinary state, and it reports
  // findings the author fixes by regenerating.
  const absent = scratch(t);
  const missing = derive(absent, ['--today', TODAY, '--json']);
  assert.equal(missing.status, 1);
  assert.deepEqual([...new Set(missing.json.findings.map((f) => f.code))], ['derived-missing']);
});

test('the loader ignores the derived directory — trees are never leaves', (t) => {
  const root = scratch(t);
  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);

  // Browse trees are markdown files under knowledge/, exactly like leaves. If
  // the loader walked them they would fail the leaf schema and the store's
  // health would depend on a directory whose contract is that deleting it
  // loses nothing.
  const validate = spawnSync(process.execPath, [join(repoRoot, 'payload', 'engine', 'validate.js'), '--root', root, '--json'], { encoding: 'utf8' });
  assert.equal(validate.status, 0, `${validate.stdout}${validate.stderr}`);
  const payload = JSON.parse(validate.stdout);
  assert.equal(payload['store-health'].errors, 0);
  assert.equal(payload['store-health'].warnings, 0, 'not even a skipped-file warning — the walk never descends');
  assert.deepEqual(payload.findings, []);
});

// ---------------------------------------------------------------- 4 · demotion

test('stale and draft leaves are annotated in the trees, never hidden', (t) => {
  const root = scratch(t);
  assert.equal(derive(root, ['--today', TODAY, '--write', '--json']).status, 0);

  for (const axis of AXES) {
    const tree = derivedFile(root, `tree.${axis.key}.md`);
    // Present, and marked.
    assert.match(tree, /`[^`]*L-000213` Component render budget — \*\*demoted\*\* \(stage\)/);
    assert.match(tree, /`[^`]*L-000162` Bundle-size budget thresholds — \*\*demoted\*\* \(time\)/);
    // Both demotions accumulate — neither absorbs the other.
    assert.match(tree, /`[^`]*L-000171` Visual regression triage playbook — \*\*demoted\*\* \(stage, time\)/);
    // The REASON travels with the mark: a demotion is never silent.
    assert.match(tree, /stage "draft" is pre-promotion/);
    assert.match(tree, /past the 90-day limit for volatile knowledge/);
  }
});

test('demoted leaves sort last within their node but stay in it', (t) => {
  const root = scratch(t);
  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);
  const tree = derivedFile(root, 'tree.domain-form.md');

  // Inside design-system/components/constraint: the promoted L-000133 precedes the
  // draft L-000213, and BOTH are in that node. Demotion reorders; it never
  // refiles and never omits.
  const constraintNode = tree.slice(tree.indexOf('**constraint/** (2)'));
  const promoted = constraintNode.indexOf('L-000133');
  const demoted = constraintNode.indexOf('L-000213');
  assert.ok(promoted !== -1 && demoted !== -1, 'both leaves stay in the node');
  assert.ok(promoted < demoted, 'the demoted leaf sorts last within its node');
});

test('without --today, staleness is skipped and SAID — never a silent pass', (t) => {
  const root = scratch(t);
  const r = derive(root, ['--write', '--json']);
  assert.equal(r.status, 0);
  assert.match(r.json['time-check'], /^skipped — no evaluation date supplied/);

  const tree = derivedFile(root, 'tree.domain-form.md');
  assert.match(tree, /- time verdicts: skipped — no evaluation date supplied/);
  // The stale-only leaf is NOT marked stale, because nothing measured it — and
  // the header says why rather than letting it read as fresh.
  assert.doesNotMatch(tree, /L-000162` Bundle-size budget thresholds — \*\*demoted\*\*/);
  // Stage demotion needs no date, so it still applies.
  assert.match(tree, /L-000213` Component render budget — \*\*demoted\*\* \(stage\)/);

  const index = JSON.parse(derivedFile(root, 'index.json'));
  const stale = index.leaves.find((l) => l.id === 'L-000162');
  assert.equal(stale.time.verdict, 'skipped');
  assert.equal(stale.demoted, false);
});

test('a leaf declaring no facets files under unclassified, visibly', (t) => {
  const root = scratch(t);
  // Strip the whole facets block from one leaf — the mid-migration state a
  // store in v1 is entirely in, and the one where a projection is most tempted
  // to guess.
  const leafPath = join(root, 'knowledge', 'brand', 'brand-color-token-table.md');
  writeFileSync(leafPath, readFileSync(leafPath, 'utf8').replace(/facets:\n(?: {2}.*\n)+/, ''));

  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);
  const tree = derivedFile(root, 'tree.domain-form.md');

  // Filed where a steward will SEE it, rather than flattening up a level into
  // the domain node and looking correctly classified.
  assert.match(tree, /- \*\*unclassified\/\*\* \(1\)/);
  assert.match(tree, /`UNC\/UNC·L-000228` Brand color token table/);
  // Still one leaf per tree: an unclassified leaf is projected, never dropped.
  assert.match(tree, /- leaves: 6$/m);
});

test('--today must be a real calendar date, and the clock is never read', (t) => {
  const root = scratch(t);
  const bad = derive(root, ['--today', '2026-02-30', '--write']);
  assert.equal(bad.status, 2, 'a date naming no day is a usage error, not a finding');
  assert.match(bad.stderr, /--today must be a real calendar date/);

  // Two runs on one injected date produce identical bytes — the wall clock
  // moved between them and nothing in the output did (D-012).
  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);
  const first = derivedFile(root, 'index.json');
  assert.equal(derive(root, ['--today', TODAY, '--write']).status, 0);
  assert.equal(derivedFile(root, 'index.json'), first);
  assert.doesNotMatch(first, /\d{4}-\d{2}-\d{2}T/, 'no timestamps anywhere');
});

// ------------------------------------------------------------- 5 · recall slot

test('the embedding-recall slot is declared, empty, and structurally gated', (t) => {
  const root = scratch(t);
  const r = derive(root, ['--today', TODAY, '--write', '--json']);
  assert.equal(r.status, 0);

  // The SLOT: its architectural position, published on every run.
  assert.deepEqual(r.json['recall-slot'], {
    status: 'declared-unimplemented',
    location: 'derived',
    consulted: 'after-deterministic-exhausted',
    output: 'proposals',
    citable: false,
    persistable: false,
    gate: 'human-review — a proposal enters the store only as an authored leaf with citations (UCS-1158)',
    'in-scope-here': 'the slot and the gate',
    'out-of-scope-here': 'model selection and semantic-recall implementation (issue #49)',
  });

  // It travels into the derived artifact too, so the position survives in the
  // layer itself rather than only in a command's stdout.
  const index = JSON.parse(derivedFile(root, 'index.json'));
  assert.equal(index['recall-slot'].citable, false);
  assert.equal(index['recall-slot'].persistable, false);
  assert.equal(index['recall-slot'].location, 'derived',
    'recall lives in the disposable layer — deleting derived/ deletes every probabilistic artifact');
});

test('the gate refuses every proposal — nothing probabilistic persists or is citable', async () => {
  const { gateProposal, RECALL_SLOT } = await import('../payload/engine/lib/derived.js');

  // Total by construction: there is no argument that admits. A recall
  // implementation routes through here and gets a refusal; the only way into
  // the store is the ordinary authoring path.
  for (const proposal of [
    { id: 'L-000117', score: 0.99 },
    { id: 'L-000133', score: 1 },
    {},
  ]) {
    const verdict = gateProposal(proposal);
    assert.equal(verdict.admitted, false);
    assert.match(verdict.reason, /never admitted automatically/);
    assert.deepEqual(verdict.proposal, proposal);
  }

  assert.equal(RECALL_SLOT.status, 'declared-unimplemented',
    'this ticket ships the slot and the gate; the implementation is out of scope by spec');
});

test('no similarity or embedding implementation ships with the derived layer', async () => {
  // The spec puts model selection and semantic recall out of scope, and the
  // failure mode is scope creep that looks helpful. This asserts the derived
  // layer computes nothing probabilistic: no vectors, no distances, no models.
  const sources = ['lib/derived.js', 'lib/call-numbers.js', 'commands/derive.js']
    .map((f) => readFileSync(join(repoRoot, 'payload', 'engine', f), 'utf8'));

  for (const source of sources) {
    // Strip comments: the position of embedding recall is DOCUMENTED here at
    // length, and the ban is on code, not on the prose that explains the slot.
    const code = source.replace(/\/\*[^]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
    for (const banned of [/cosine/i, /embedding\s*\(/i, /similarity\s*\(/i, /\bnorm\s*\(/i, /openai|anthropic|transformer/i]) {
      assert.doesNotMatch(code, banned, `the derived layer must not implement recall (matched ${banned})`);
    }
  }
});
